<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>Rekap HR Perusahaan</title><style>
*{font-family:DejaVu Sans,sans-serif}body{font-size:10px;color:#1e293b}h1{margin:0;font-size:22px}h2{margin:4px 0 0;font-size:14px;color:#64748b}.meta{margin:8px 0 18px;color:#64748b}.summary{width:100%;border-collapse:collapse;margin-bottom:18px}.summary td{border:1px solid #dbe3ef;padding:9px;text-align:center}.summary strong{display:block;font-size:18px;color:#1d4ed8}.summary span{font-size:9px;color:#64748b}table.data{width:100%;border-collapse:collapse}table.data th{background:#1d4ed8;color:white;padding:7px;font-size:8px}table.data td{border:1px solid #e2e8f0;padding:6px;font-size:8px}table.data tr:nth-child(even){background:#f8fafc}.right{text-align:right}.center{text-align:center}.footer{position:fixed;bottom:-12px;left:0;right:0;text-align:center;color:#94a3b8;font-size:8px}
</style></head><body>
<h1>Rekapitulasi HR Perusahaan</h1><h2>{{ $company->name }}</h2><div class="meta">Periode: {{ $recap['range']['label'] }} · {{ $recap['range']['working_days'] }} hari kerja · Dibuat: {{ now()->format('d/m/Y H:i') }}</div>
<table class="summary"><tr><td><strong>{{ $recap['summary']['employees'] }}</strong><span>Employee</span></td><td><strong>{{ number_format($recap['summary']['attendance_rate'],1) }}%</strong><span>Attendance Rate</span></td><td><strong>{{ $recap['summary']['absent'] }}</strong><span>Absent</span></td><td><strong>{{ $recap['summary']['assignment_total'] }}</strong><span>Assignment</span></td><td><strong>{{ number_format($recap['summary']['completion_rate'],1) }}%</strong><span>Completion Rate</span></td><td><strong>{{ $recap['summary']['assignment_not_worked'] }}</strong><span>Not Worked</span></td></tr></table>
<table class="data"><thead><tr><th>No</th><th>Employee</th><th>Department / Position</th><th>Hadir</th><th>Telat</th><th>Absent</th><th>Attendance</th><th>Assignment</th><th>Completed</th><th>Rejected</th><th>Not Worked</th><th>Completion</th><th>Skor</th></tr></thead><tbody>
@forelse($recap['rows'] as $index => $row)<tr><td class="center">{{ $index+1 }}</td><td><strong>{{ $row['employee_name'] }}</strong><br>{{ $row['employee_number'] }}</td><td>{{ $row['department'] }}<br>{{ $row['position'] }}</td><td class="center">{{ $row['attended'] }}/{{ $row['working_days'] }}</td><td class="center">{{ $row['late'] }}</td><td class="center">{{ $row['absent'] }}</td><td class="right">{{ number_format($row['attendance_rate'],1) }}%</td><td class="center">{{ $row['assignment_total'] }}</td><td class="center">{{ $row['assignment_completed'] }}</td><td class="center">{{ $row['assignment_rejected'] }}</td><td class="center">{{ $row['assignment_not_worked'] }}</td><td class="right">{{ number_format($row['completion_rate'],1) }}%</td><td class="right">{{ number_format($row['performance_score'],1) }}</td></tr>@empty<tr><td colspan="13" class="center">Tidak ada data.</td></tr>@endforelse
</tbody></table><div class="footer">Generated automatically by Smart Workforce Management System (SWMS)</div></body></html>
